using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Sonneville.PriceTools;

namespace Sonneville.PriceToolsTest
{
    [TestClass]
    public class EntityFramework
    {
        [TestMethod]
        public void TestCreateEntityMethods()
        {
            /////////////////////////////////////////////////////////////////////
            // The sole purpose of this test is to ensure code coverage        //
            // for the Create{Entity}() methods generated by Entity Framework. //
            //                                                                 //
            // No actual testing takes place. Initialize with empty data.      //
            /////////////////////////////////////////////////////////////////////

            var date = DateTime.Now;
            const string text = "John";

            Buy.CreateBuy(0, date, 0, 0, 0, text);
            BuyToCover.CreateBuyToCover(0, date, 0, 0, 0, text);
            Deposit.CreateDeposit(0, date, 0);
            DividendReceipt.CreateDividendReceipt(0, date, 0);
            DividendReinvestment.CreateDividendReinvestment(0, date, 0, 0, 0, text);
            Sell.CreateSell(0, date, 0, 0, 0, text);
            SellShort.CreateSellShort(0, date, 0, 0, 0, text);
            Withdrawal.CreateWithdrawal(0, date, 0);

            CashAccount.CreateCashAccount(0);
            Position.CreatePosition(0, text);
            Portfolio.CreatePortfolio(0, text);

            PriceQuote.CreatePriceQuote(0, date, 0);
            PriceSeries.CreatePriceSeries(0);
        }
    }
}
