//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonneville.PriceToolsTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonneville.PriceToolsTest.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2011-03-15,84.90,88.03,84.27,87.68,4658900,87.68
        ///2011-03-14,87.72,88.13,86.44,87.63,3922600,87.63
        ///2011-03-11,85.88,88.00,84.59,87.79,6210200,87.79
        ///2011-03-10,88.01,89.00,86.10,87.55,5686400,87.55
        ///2011-03-09,90.42,90.64,89.00,89.82,4702100,89.82
        ///2011-03-08,90.58,92.10,88.90,91.51,4183100,91.51
        ///2011-03-07,92.91,93.15,89.94,90.37,4207200,90.37
        ///2011-03-04,92.73,93.06,91.11,92.35,3610400,92.35
        ///2011-03-03,90.87,93.16,90.43,92.63,4846300,92.63
        ///2011-03-02,88.76,90.67,88.70, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DE_PriceData_Yahoo {
            get {
                return ResourceManager.GetString("DE_PriceData_Yahoo", resourceCulture);
            }
        }
        
        internal static byte[] FidelityTransactions {
            get {
                object obj = ResourceManager.GetObject("FidelityTransactions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SPX_8_Dec_2010_to_10_Dec_2010 {
            get {
                object obj = ResourceManager.GetObject("SPX_8_Dec_2010_to_10_Dec_2010", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SPX_price_24_aug_2010 {
            get {
                object obj = ResourceManager.GetObject("SPX_price_24_aug_2010", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
