//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.IO;

namespace Sonneville.PriceToolsTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonneville.PriceToolsTest.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Date,Action,Transaction Type,Symbol,Security Description,Security Type,Quantity,Price ($),Commission ($),Fees ($),Accrued Interest ($),Amount ($),Settlement Date
        /// 10/01/2010, TRANSFERRED FROM     TO BROKERAGE OPTION,Cash, ,  ,Cash,,,,,,297.19,
        /// 09/30/2010, DIVIDEND RECEIVED,Dividend, FDRXX, FIDELITY CASH RESERVES,Cash,,,,,,0.6,
        /// 09/30/2010, REINVESTMENT,Reinvestment, FDRXX, FIDELITY CASH RESERVES,Cash,0.6,1,,,,-0.6,
        /// 09/13/2010, YOU BOUGHT           PROSPECTUS UNDER    SEPARATE COVER,Buy, FSRFX, F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FidelityTransactions {
            get {
                return ResourceManager.GetString("FidelityTransactions", resourceCulture);
            }
        }
        
        internal static byte[] SPX_price_24_aug_2010 {
            get {
                object obj = ResourceManager.GetObject("SPX_price_24_aug_2010", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static byte[] SPX_8_Dec_2010_to_10_Dec_2010 {
            get {
                object obj = ResourceManager.GetObject("SPX_8_Dec_2010_to_10_Dec_2010", resourceCulture);
                return ((byte[]) (obj));
            }
        }
    }
}
