//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonneville.PriceTools.SamplePortfolioData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FidelityData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FidelityData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonneville.PriceTools.SamplePortfolioData.FidelityData", typeof(FidelityData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Date,Action Description,Symbol,Security Description,Security Type,Quantity,Price ($),Commission ($),Fees ($),Accrued Interest ($),Amount ($),Settlement Date
        ///4/17/2008, TRANSFERRED FROM     TO BROKERAGE OPTION, ,  ,Cash,,,,,,4683.93, 
        ///4/29/2008, YOU BOUGHT           PROSPECTUS UNDER    SEPARATE COVER, FEMKX, FIDELITY EMERGING MARKETS,Cash,34.669,31.39,,,,-1088.25, 04/30/2008
        ///4/29/2008, YOU BOUGHT           PROSPECTUS UNDER    SEPARATE COVER, FICDX, FIDELITY CANADA,Cash,11.364,59.95,,,,-681.25, 04/30 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BrokerageLink_trades {
            get {
                return ResourceManager.GetString("BrokerageLink_trades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Date,Action Description,Action,Symbol,Security Description,Security Type,Quantity,Price ($),Commission ($),Fees ($),Accrued Interest ($),Amount ($),Settlement Date
        ///4/29/2008, YOU BOUGHT           PROSPECTUS UNDER    SEPARATE COVER,BUY, FSAGX, FIDELITY SELECT GOLD,Cash,13.291,37.62,,,,-500, 04/30/2008
        ///.
        /// </summary>
        internal static string BrokerageLink_TransactionPriceRounding {
            get {
                return ResourceManager.GetString("BrokerageLink_TransactionPriceRounding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade Date,Action,Symbol,Security Description,Security Type,Quantity,Price ($),Commission ($),Fees ($),Accrued Interest ($),Amount ($),Settlement Date
        ///5/17/2010, Electronic Funds Transfer Received, ,  ,Cash,,,,,,400,
        ///6/16/2010, Electronic Funds Transfer Received, ,  ,Cash,,,,,,400,
        ///7/16/2010, Electronic Funds Transfer Received, ,  ,Cash,,,,,,400, 
        ///7/30/2010, DIVIDEND RECEIVED, FTEXX, FIDELITY MUNICIPAL MONEY MARKET,Cash,,,,,,0.01, 
        ///7/30/2010, REINVESTMENT, FTEXX, FIDELITY MUNICIPAL MONEY MARKET,Cash,0. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FidelityTransactions {
            get {
                return ResourceManager.GetString("FidelityTransactions", resourceCulture);
            }
        }
    }
}
