//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PriceAnalyzerTest {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PriceAnalyzerTest.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume
        ///29-Jun-11,82.59,82.99,81.78,82.43,6328726
        ///28-Jun-11,80.84,82,80.5,81.95,3153729
        ///27-Jun-11,80.15,81.06,79.96,80.69,3177440
        ///24-Jun-11,81.66,81.7,79.78,79.98,4672971
        ///23-Jun-11,79.85,81.84,78.8,81.73,5785469
        ///22-Jun-11,82.19,83,81.5,81.57,4885633
        ///21-Jun-11,80.69,82.44,80.3,82.13,4299825
        ///20-Jun-11,78.28,80.09,77.81,80.06,4329004
        ///17-Jun-11,80.48,80.53,78.3,78.53,5972507
        ///16-Jun-11,80.1,80.84,78.23,79.27,5510531
        ///15-Jun-11,81.36,82.18,80.09,80.21,4538246
        ///14-Jun-11,81.55,82. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DE_1_1_2011_to_6_30_2011 {
            get {
                return ResourceManager.GetString("DE_1_1_2011_to_6_30_2011", resourceCulture);
            }
        }
    }
}
