//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonneville.PriceTools.SampleData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CsvPriceData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CsvPriceData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonneville.PriceTools.SampleData.CsvPriceData", typeof(CsvPriceData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume
        ///3-Jan-11,83.93,84.75,83.46,83.59,3006992
        ///4-Jan-11,84,84.08,81.8,83.02,3117469
        ///5-Jan-11,82.42,84.64,82.28,84.24,3020762
        ///6-Jan-11,84.41,84.68,83.46,84.25,3528211
        ///7-Jan-11,84.42,85.3,83.3,84.34,4061529
        ///10-Jan-11,84.69,85.3,83.65,84.58,2958568
        ///11-Jan-11,85.19,86.65,85.19,85.66,3357624
        ///12-Jan-11,86.56,87.74,86.54,87.45,3283946
        ///13-Jan-11,89.24,89.97,88.75,89.47,6106721
        ///14-Jan-11,89.52,89.52,89.52,89.52,0
        ///18-Jan-11,89.69,91.63,89.69,90.6,4488671
        ///19-Jan-11,90.5,91.28,88.7 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DE_1_1_2011_to_6_30_2011 {
            get {
                return ResourceManager.GetString("DE_1_1_2011_to_6_30_2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2014-03-05,99.00,99.00,99.00,99.00,000,99.00
        ///2014-03-04,98.90,98.90,98.90,98.90,000,98.90
        ///2014-03-03,97.29,97.29,97.29,97.29,000,97.29
        ///2014-02-28,98.20,98.20,98.20,98.20,000,98.20
        ///2014-02-27,98.19,98.19,98.19,98.19,000,98.19
        ///2014-02-26,97.70,97.70,97.70,97.70,000,97.70
        ///2014-02-25,97.72,97.72,97.72,97.72,000,97.72
        ///2014-02-24,97.55,97.55,97.55,97.55,000,97.55
        ///2014-02-21,96.78,96.78,96.78,96.78,000,96.78
        ///2014-02-20,96.70,96.70,96.70,96.70,000,96.70
        ///2014-02-19,96.14,96. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FCNTX {
            get {
                return ResourceManager.GetString("FCNTX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2014-03-05,135.76,135.76,135.76,135.76,000,135.76
        ///2014-03-04,136.13,136.13,136.13,136.13,000,136.13
        ///2014-03-03,134.14,134.14,134.14,134.14,000,134.14
        ///2014-02-28,135.05,135.05,135.05,135.05,000,135.05
        ///2014-02-27,134.98,134.98,134.98,134.98,000,134.98
        ///2014-02-26,133.87,133.87,133.87,133.87,000,133.87
        ///2014-02-25,133.60,133.60,133.60,133.60,000,133.60
        ///2014-02-24,133.80,133.80,133.80,133.80,000,133.80
        ///2014-02-21,132.48,132.48,132.48,132.48,000,132.48
        ///2014-02-20,131.96,13 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FDLSX {
            get {
                return ResourceManager.GetString("FDLSX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2014-03-05,8.83,8.83,8.83,8.83,000,8.83
        ///2014-03-04,8.79,8.79,8.79,8.79,000,8.79
        ///2014-03-03,8.54,8.54,8.54,8.54,000,8.54
        ///2014-02-28,8.97,8.97,8.97,8.97,000,8.97
        ///2014-02-27,8.96,8.96,8.96,8.96,000,8.96
        ///2014-02-26,8.94,8.94,8.94,8.94,000,8.94
        ///2014-02-25,9.03,9.03,9.03,9.03,000,9.03
        ///2014-02-24,9.04,9.04,9.04,9.04,000,9.04
        ///2014-02-21,8.95,8.95,8.95,8.95,000,8.95
        ///2014-02-20,8.86,8.86,8.86,8.86,000,8.86
        ///2014-02-19,8.90,8.90,8.90,8.90,000,8.90
        ///2014-02-18,8.99,8.99,8.99,8.99 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FEMEX {
            get {
                return ResourceManager.GetString("FEMEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2014-03-05,23.69,23.69,23.69,23.69,000,23.69
        ///2014-03-04,23.62,23.62,23.62,23.62,000,23.62
        ///2014-03-03,23.24,23.24,23.24,23.24,000,23.24
        ///2014-02-28,23.69,23.69,23.69,23.69,000,23.69
        ///2014-02-27,23.56,23.56,23.56,23.56,000,23.56
        ///2014-02-26,23.34,23.34,23.34,23.34,000,23.34
        ///2014-02-25,23.29,23.29,23.29,23.29,000,23.29
        ///2014-02-24,23.26,23.26,23.26,23.26,000,23.26
        ///2014-02-21,23.21,23.21,23.21,23.21,000,23.21
        ///2014-02-20,23.04,23.04,23.04,23.04,000,23.04
        ///2014-02-19,23.14,23. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FEMKX {
            get {
                return ResourceManager.GetString("FEMKX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2014-03-05,33.99,33.99,33.99,33.99,000,33.99
        ///2014-03-04,33.96,33.96,33.96,33.96,000,33.96
        ///2014-03-03,33.56,33.56,33.56,33.56,000,33.56
        ///2014-02-28,33.85,33.85,33.85,33.85,000,33.85
        ///2014-02-27,33.67,33.67,33.67,33.67,000,33.67
        ///2014-02-26,33.16,33.16,33.16,33.16,000,33.16
        ///2014-02-25,32.81,32.81,32.81,32.81,000,32.81
        ///2014-02-24,32.88,32.88,32.88,32.88,000,32.88
        ///2014-02-21,33.25,33.25,33.25,33.25,000,33.25
        ///2014-02-20,33.29,33.29,33.29,33.29,000,33.29
        ///2014-02-19,33.43,33. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FHKCX {
            get {
                return ResourceManager.GetString("FHKCX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2014-03-05,59.25,59.25,59.25,59.25,000,59.25
        ///2014-03-04,58.91,58.91,58.91,58.91,000,58.91
        ///2014-03-03,58.60,58.60,58.60,58.60,000,58.60
        ///2014-02-28,58.67,58.67,58.67,58.67,000,58.67
        ///2014-02-27,58.55,58.55,58.55,58.55,000,58.55
        ///2014-02-26,58.41,58.41,58.41,58.41,000,58.41
        ///2014-02-25,58.57,58.57,58.57,58.57,000,58.57
        ///2014-02-24,58.90,58.90,58.90,58.90,000,58.90
        ///2014-02-21,58.54,58.54,58.54,58.54,000,58.54
        ///2014-02-20,58.76,58.76,58.76,58.76,000,58.76
        ///2014-02-19,58.34,58. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FICDX {
            get {
                return ResourceManager.GetString("FICDX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2014-03-05,28.56,28.56,28.56,28.56,000,28.56
        ///2014-03-04,28.37,28.37,28.37,28.37,000,28.37
        ///2014-03-03,27.92,27.92,27.92,27.92,000,27.92
        ///2014-02-28,28.46,28.46,28.46,28.46,000,28.46
        ///2014-02-27,28.68,28.68,28.68,28.68,000,28.68
        ///2014-02-26,28.22,28.22,28.22,28.22,000,28.22
        ///2014-02-25,28.38,28.38,28.38,28.38,000,28.38
        ///2014-02-24,28.68,28.68,28.68,28.68,000,28.68
        ///2014-02-21,28.59,28.59,28.59,28.59,000,28.59
        ///2014-02-20,28.38,28.38,28.38,28.38,000,28.38
        ///2014-02-19,28.33,28. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FLATX {
            get {
                return ResourceManager.GetString("FLATX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2014-03-05,150.26,150.26,150.26,150.26,000,150.26
        ///2014-03-04,150.07,150.07,150.07,150.07,000,150.07
        ///2014-03-03,148.09,148.09,148.09,148.09,000,148.09
        ///2014-02-28,148.22,148.22,148.22,148.22,000,148.22
        ///2014-02-27,147.46,147.46,147.46,147.46,000,147.46
        ///2014-02-26,146.26,146.26,146.26,146.26,000,146.26
        ///2014-02-25,145.24,145.24,145.24,145.24,000,145.24
        ///2014-02-24,144.52,144.52,144.52,144.52,000,144.52
        ///2014-02-21,144.84,144.84,144.84,144.84,000,144.84
        ///2014-02-20,144.93,14 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FSCHX {
            get {
                return ResourceManager.GetString("FSCHX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2014-03-05,72.78,72.78,72.78,72.78,000,72.78
        ///2014-03-04,72.70,72.70,72.70,72.70,000,72.70
        ///2014-03-03,71.05,71.05,71.05,71.05,000,71.05
        ///2014-02-28,71.99,71.99,71.99,71.99,000,71.99
        ///2014-02-27,71.82,71.82,71.82,71.82,000,71.82
        ///2014-02-26,71.20,71.20,71.20,71.20,000,71.20
        ///2014-02-25,71.55,71.55,71.55,71.55,000,71.55
        ///2014-02-24,72.36,72.36,72.36,72.36,000,72.36
        ///2014-02-21,71.58,71.58,71.58,71.58,000,71.58
        ///2014-02-20,71.61,71.61,71.61,71.61,000,71.61
        ///2014-02-19,71.26,71. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FSLBX {
            get {
                return ResourceManager.GetString("FSLBX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2014-03-05,39.28,39.28,39.28,39.28,000,39.28
        ///2014-03-04,39.42,39.42,39.42,39.42,000,39.42
        ///2014-03-03,39.03,39.03,39.03,39.03,000,39.03
        ///2014-02-28,39.16,39.16,39.16,39.16,000,39.16
        ///2014-02-27,38.79,38.79,38.79,38.79,000,38.79
        ///2014-02-26,38.80,38.80,38.80,38.80,000,38.80
        ///2014-02-25,39.00,39.00,39.00,39.00,000,39.00
        ///2014-02-24,39.17,39.17,39.17,39.17,000,39.17
        ///2014-02-21,38.65,38.65,38.65,38.65,000,38.65
        ///2014-02-20,38.85,38.85,38.85,38.85,000,38.85
        ///2014-02-19,38.74,38. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FSNGX {
            get {
                return ResourceManager.GetString("FSNGX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2014-03-05,89.00,89.00,89.00,89.00,000,89.00
        ///2014-03-04,88.95,88.95,88.95,88.95,000,88.95
        ///2014-03-03,87.58,87.58,87.58,87.58,000,87.58
        ///2014-02-28,88.18,88.18,88.18,88.18,000,88.18
        ///2014-02-27,88.33,88.33,88.33,88.33,000,88.33
        ///2014-02-26,87.79,87.79,87.79,87.79,000,87.79
        ///2014-02-25,87.75,87.75,87.75,87.75,000,87.75
        ///2014-02-24,87.68,87.68,87.68,87.68,000,87.68
        ///2014-02-21,87.05,87.05,87.05,87.05,000,87.05
        ///2014-02-20,87.08,87.08,87.08,87.08,000,87.08
        ///2014-02-19,86.48,86. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string FTRNX {
            get {
                return ResourceManager.GetString("FTRNX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2011-03-15,157.35,159.64,156.88,159.02,6475800,155.73
        ///2011-03-14,161.16,161.98,160.09,161.39,4300500,158.05
        ///2011-03-11,162.40,163.24,160.84,162.43,4271000,159.07
        ///2011-03-10,164.64,164.67,161.38,162.02,7041400,158.67
        ///2011-03-09,163.47,167.72,163.28,165.86,9086600,162.43
        ///2011-03-08,159.70,163.43,159.21,162.28,5384800,158.93
        ///2011-03-07,161.60,162.98,158.85,159.93,5312000,156.62
        ///2011-03-04,163.40,164.31,160.65,161.83,4910700,158.49
        ///2011-03-03,161.42,164.00,161.27,163.48 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IBM_1_1_2011_to_3_15_2011_Daily_Yahoo {
            get {
                return ResourceManager.GetString("IBM_1_1_2011_to_3_15_2011_Daily_Yahoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2011-03-14,161.16,161.98,156.88,159.02,5388100,151.46
        ///2011-03-07,161.60,167.72,158.85,162.43,6219100,154.70
        ///2011-02-28,162.36,164.31,159.41,161.83,4307400,154.13
        ///2011-02-22,163.57,164.26,159.03,162.28,5358300,154.56
        ///2011-02-14,164.18,164.84,162.52,164.84,3718000,157.00
        ///2011-02-07,164.08,166.25,163.18,163.85,5219400,156.06
        ///2011-01-31,159.18,164.20,158.68,164.00,5074200,155.58
        ///2011-01-24,155.42,164.35,155.33,159.21,6500500,151.04
        ///2011-01-18,149.82,156.78,149.38,155.50 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string IBM_1_1_2011_to_3_15_2011_Weekly_Yahoo {
            get {
                return ResourceManager.GetString("IBM_1_1_2011_to_3_15_2011_Weekly_Yahoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2012-08-07,199.43,200.88,198.80,199.93,3209400,194.44
        ///.
        /// </summary>
        public static string IBM_8_7_2012_to_8_7_2012_Daily_Yahoo {
            get {
                return ResourceManager.GetString("IBM_8_7_2012_to_8_7_2012_Daily_Yahoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume
        ///1-Jul-11,24.23,26.02,24.23,26.02,291664498
        ///24-Jun-11,24.17,24.86,24.16,24.30,309206180
        ///17-Jun-11,23.79,29.05,23.65,24.26,280430166
        ///10-Jun-11,23.90,24.25,23.69,23.70,230307366
        ///3-Jun-11,24.96,25.10,23.84,23.90,246418070
        ///27-May-11,24.21,25.03,24.03,24.76,213316051
        ///20-May-11,24.96,25.07,24.25,24.49,311462943
        ///13-May-11,25.80,25.96,24.95,25.03,382293426
        ///6-May-11,25.94,26.25,25.48,25.87,346656165
        ///29-Apr-11,25.56,26.87,25.34,25.92,554889924
        ///21-Apr-11,25.10,26.00,24.72,25.52,158547201 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string MSFT_Apr_June_2011_Weekly_Google {
            get {
                return ResourceManager.GetString("MSFT_Apr_June_2011_Weekly_Google", resourceCulture);
            }
        }
    }
}
