//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonneville.PriceTools.SampleData {
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CsvPriceData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CsvPriceData() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonneville.PriceTools.SampleData.CsvPriceData", typeof(CsvPriceData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string DE_1_1_2011_to_6_30_2011 {
            get {
                return ResourceManager.GetString("DE_1_1_2011_to_6_30_2011", resourceCulture);
            }
        }
        
        public static string FCNTX {
            get {
                return ResourceManager.GetString("FCNTX", resourceCulture);
            }
        }
        
        public static string FDLSX {
            get {
                return ResourceManager.GetString("FDLSX", resourceCulture);
            }
        }
        
        public static string FEMEX {
            get {
                return ResourceManager.GetString("FEMEX", resourceCulture);
            }
        }
        
        public static string FEMKX {
            get {
                return ResourceManager.GetString("FEMKX", resourceCulture);
            }
        }
        
        public static string FHKCX {
            get {
                return ResourceManager.GetString("FHKCX", resourceCulture);
            }
        }
        
        public static string FICDX {
            get {
                return ResourceManager.GetString("FICDX", resourceCulture);
            }
        }
        
        public static string FLATX {
            get {
                return ResourceManager.GetString("FLATX", resourceCulture);
            }
        }
        
        public static string FSCHX {
            get {
                return ResourceManager.GetString("FSCHX", resourceCulture);
            }
        }
        
        public static string FSLBX {
            get {
                return ResourceManager.GetString("FSLBX", resourceCulture);
            }
        }
        
        public static string FSNGX {
            get {
                return ResourceManager.GetString("FSNGX", resourceCulture);
            }
        }
        
        public static string FTRNX {
            get {
                return ResourceManager.GetString("FTRNX", resourceCulture);
            }
        }
        
        public static string IBM_1_1_2011_to_3_15_2011_Daily_Yahoo {
            get {
                return ResourceManager.GetString("IBM_1_1_2011_to_3_15_2011_Daily_Yahoo", resourceCulture);
            }
        }
        
        public static string IBM_1_1_2011_to_3_15_2011_Weekly_Yahoo {
            get {
                return ResourceManager.GetString("IBM_1_1_2011_to_3_15_2011_Weekly_Yahoo", resourceCulture);
            }
        }
        
        public static string IBM_8_7_2012_to_8_7_2012_Daily_Yahoo {
            get {
                return ResourceManager.GetString("IBM_8_7_2012_to_8_7_2012_Daily_Yahoo", resourceCulture);
            }
        }
        
        public static string MSFT_Apr_June_2011_Weekly_Google {
            get {
                return ResourceManager.GetString("MSFT_Apr_June_2011_Weekly_Google", resourceCulture);
            }
        }
    }
}
