//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonneville.PriceTools.SampleData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CsvPriceData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CsvPriceData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonneville.PriceTools.SampleData.CsvPriceData", typeof(CsvPriceData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume
        ///3-Jan-11,83.93,84.75,83.46,83.59,3006992
        ///4-Jan-11,84,84.08,81.8,83.02,3117469
        ///5-Jan-11,82.42,84.64,82.28,84.24,3020762
        ///6-Jan-11,84.41,84.68,83.46,84.25,3528211
        ///7-Jan-11,84.42,85.3,83.3,84.34,4061529
        ///10-Jan-11,84.69,85.3,83.65,84.58,2958568
        ///11-Jan-11,85.19,86.65,85.19,85.66,3357624
        ///12-Jan-11,86.56,87.74,86.54,87.45,3283946
        ///13-Jan-11,89.24,89.97,88.75,89.47,6106721
        ///14-Jan-11,89.52,89.52,89.52,89.52,0
        ///18-Jan-11,89.69,91.63,89.69,90.6,4488671
        ///19-Jan-11,90.5,91.28,88.7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DE_1_1_2011_to_6_30_2011 {
            get {
                return ResourceManager.GetString("DE_1_1_2011_to_6_30_2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2011-03-15,157.35,159.64,156.88,159.02,6475800,155.73
        ///2011-03-14,161.16,161.98,160.09,161.39,4300500,158.05
        ///2011-03-11,162.40,163.24,160.84,162.43,4271000,159.07
        ///2011-03-10,164.64,164.67,161.38,162.02,7041400,158.67
        ///2011-03-09,163.47,167.72,163.28,165.86,9086600,162.43
        ///2011-03-08,159.70,163.43,159.21,162.28,5384800,158.93
        ///2011-03-07,161.60,162.98,158.85,159.93,5312000,156.62
        ///2011-03-04,163.40,164.31,160.65,161.83,4910700,158.49
        ///2011-03-03,161.42,164.00,161.27,163.48 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IBM_1_1_2011_to_3_15_2011_Daily_Yahoo {
            get {
                return ResourceManager.GetString("IBM_1_1_2011_to_3_15_2011_Daily_Yahoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2011-03-14,161.16,161.98,156.88,159.02,5388100,151.46
        ///2011-03-07,161.60,167.72,158.85,162.43,6219100,154.70
        ///2011-02-28,162.36,164.31,159.41,161.83,4307400,154.13
        ///2011-02-22,163.57,164.26,159.03,162.28,5358300,154.56
        ///2011-02-14,164.18,164.84,162.52,164.84,3718000,157.00
        ///2011-02-07,164.08,166.25,163.18,163.85,5219400,156.06
        ///2011-01-31,159.18,164.20,158.68,164.00,5074200,155.58
        ///2011-01-24,155.42,164.35,155.33,159.21,6500500,151.04
        ///2011-01-18,149.82,156.78,149.38,155.50 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IBM_1_1_2011_to_3_15_2011_Weekly_Yahoo {
            get {
                return ResourceManager.GetString("IBM_1_1_2011_to_3_15_2011_Weekly_Yahoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2012-08-07,199.43,200.88,198.80,199.93,3209400,194.44
        ///.
        /// </summary>
        internal static string IBM_8_7_2012_to_8_7_2012_Daily_Yahoo {
            get {
                return ResourceManager.GetString("IBM_8_7_2012_to_8_7_2012_Daily_Yahoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume
        ///1-Jul-11,24.23,26.02,24.23,26.02,291664498
        ///24-Jun-11,24.17,24.86,24.16,24.30,309206180
        ///17-Jun-11,23.79,29.05,23.65,24.26,280430166
        ///10-Jun-11,23.90,24.25,23.69,23.70,230307366
        ///3-Jun-11,24.96,25.10,23.84,23.90,246418070
        ///27-May-11,24.21,25.03,24.03,24.76,213316051
        ///20-May-11,24.96,25.07,24.25,24.49,311462943
        ///13-May-11,25.80,25.96,24.95,25.03,382293426
        ///6-May-11,25.94,26.25,25.48,25.87,346656165
        ///29-Apr-11,25.56,26.87,25.34,25.92,554889924
        ///21-Apr-11,25.10,26.00,24.72,25.52,158547201 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MSFT_Apr_June_2011_Weekly_Google {
            get {
                return ResourceManager.GetString("MSFT_Apr_June_2011_Weekly_Google", resourceCulture);
            }
        }
    }
}
