using System;

namespace Sonneville.PriceTools.Trading
{
    /// <summary>
    /// An order generated by a <see cref="TradingStrategy"/>.
    /// </summary>
    public sealed class OrderInfo : EventArgs
    {
        public OrderInfo(DateTime expiration, string ticker, decimal limitPrice, DateTime issued)
        {
            Expiration = expiration;
            LimitPrice = limitPrice;
            Ticker = ticker;
            Issued = issued;
        }

        /// <summary>
        /// The ticker symbol for this order.
        /// </summary>
        public string Ticker { get; private set; }

        /// <summary>
        /// The DateTime this order was issued.
        /// </summary>
        public DateTime Issued { get; private set; }

        /// <summary>
        /// The DateTime this order expires.
        /// </summary>
        public DateTime Expiration { get; private set; }

        /// <summary>
        /// The limit price at which the order should be executed.
        /// </summary>
        public decimal LimitPrice { get; private set; }
    }
}