//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonneville.PriceTools.Trading {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonneville.PriceTools.Trading.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OrderType..
        /// </summary>
        internal static string Order_Order_Invalid_OrderType_ {
            get {
                return ResourceManager.GetString("Order_Order_Invalid_OrderType_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PricingType..
        /// </summary>
        internal static string Order_Order_Invalid_PricingType_ {
            get {
                return ResourceManager.GetString("Order_Order_Invalid_PricingType_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OrderType must be Buy, Sell, SellShort, or BuyToClose..
        /// </summary>
        internal static string Order_Order_OrderType_must_be_Buy__Sell__SellShort__or_BuyToClose_ {
            get {
                return ResourceManager.GetString("Order_Order_OrderType_must_be_Buy__Sell__SellShort__or_BuyToClose_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be a positive number..
        /// </summary>
        internal static string Order_Validate_Price_must_be_a_positive_number_ {
            get {
                return ResourceManager.GetString("Order_Validate_Price_must_be_a_positive_number_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares must be a positive number..
        /// </summary>
        internal static string Order_Validate_Shares_must_be_a_positive_number_ {
            get {
                return ResourceManager.GetString("Order_Validate_Shares_must_be_a_positive_number_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot execute this order..
        /// </summary>
        internal static string TradingAccount_Submit_Cannot_execute_this_order_ {
            get {
                return ResourceManager.GetString("TradingAccount_Submit_Cannot_execute_this_order_", resourceCulture);
            }
        }
    }
}
