//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonneville.PriceTools.SamplePriceData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CsvPriceData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CsvPriceData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonneville.PriceTools.SamplePriceData.CsvPriceData", typeof(CsvPriceData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2011-03-15,84.90,88.03,84.27,87.68,4658900,87.68
        ///2011-03-14,87.72,88.13,86.44,87.63,3922600,87.63
        ///2011-03-11,85.88,88.00,84.59,87.79,6210200,87.79
        ///2011-03-10,88.01,89.00,86.10,87.55,5686400,87.55
        ///2011-03-09,90.42,90.64,89.00,89.82,4702100,89.82
        ///2011-03-08,90.58,92.10,88.90,91.51,4183100,91.51
        ///2011-03-07,92.91,93.15,89.94,90.37,4207200,90.37
        ///2011-03-04,92.73,93.06,91.11,92.35,3610400,92.35
        ///2011-03-03,90.87,93.16,90.43,92.63,4846300,92.63
        ///2011-03-02,88.76,90.67,88.70, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DE_1_1_2011_to_3_15_2011_Daily_Yahoo {
            get {
                return ResourceManager.GetString("DE_1_1_2011_to_3_15_2011_Daily_Yahoo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume
        ///3-Jan-11,83.93,84.75,83.46,83.59,3006992
        ///4-Jan-11,84,84.08,81.8,83.02,3117469
        ///5-Jan-11,82.42,84.64,82.28,84.24,3020762
        ///6-Jan-11,84.41,84.68,83.46,84.25,3528211
        ///7-Jan-11,84.42,85.3,83.3,84.34,4061529
        ///10-Jan-11,84.69,85.3,83.65,84.58,2958568
        ///11-Jan-11,85.19,86.65,85.19,85.66,3357624
        ///12-Jan-11,86.56,87.74,86.54,87.45,3283946
        ///13-Jan-11,89.24,89.97,88.75,89.47,6106721
        ///14-Jan-11,89.52,89.52,89.52,89.52,0
        ///18-Jan-11,89.69,91.63,89.69,90.6,4488671
        ///19-Jan-11,90.5,91.28,88.7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DE_1_1_2011_to_6_30_2011 {
            get {
                return ResourceManager.GetString("DE_1_1_2011_to_6_30_2011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume
        ///1-Jul-11,80.15,84.54,79.96,84.54,20157505
        ///24-Jun-11,78.28,83.00,77.80,79.98,23972902
        ///17-Jun-11,81.67,82.66,78.23,78.53,25327660
        ///10-Jun-11,82.12,82.79,79.61,81.80,27920378
        ///3-Jun-11,87.06,87.15,81.52,82.20,21932073
        ///27-May-11,83.02,85.74,82.25,85.74,20512786
        ///20-May-11,87.33,89.45,84.27,84.75,36884412
        ///13-May-11,91.59,94.61,87.57,87.72,24815261
        ///6-May-11,98.22,98.30,91.00,91.53,22927128
        ///29-Apr-11,95.20,97.78,94.20,97.50,16747373
        ///21-Apr-11,92.53,95.25,90.65,95.25,12189413
        ///15-Apr-11, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DE_Apr_June_2011_Weekly_Google {
            get {
                return ResourceManager.GetString("DE_Apr_June_2011_Weekly_Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2010-12-10,71.31,71.55,70.32,71.52,360200,71.52
        ///2010-12-09,71.47,71.51,70.65,71.00,251600,71.00
        ///2010-12-08,71.17,71.57,70.48,70.90,273400,70.90
        ///.
        /// </summary>
        internal static string SPX_8_Dec_2010_to_10_Dec_2010 {
            get {
                return ResourceManager.GetString("SPX_8_Dec_2010_to_10_Dec_2010", resourceCulture);
            }
        }
    }
}
