//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonneville.PriceTools.Data {
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonneville.PriceTools.Data.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DownloadPricesToCsv_InternetAccessFailed {
            get {
                return ResourceManager.GetString("DownloadPricesToCsv_InternetAccessFailed", resourceCulture);
            }
        }
        
        internal static string ParseError_CSV_data_is_corrupt__closing_price_cannot_be_null_for_any_period {
            get {
                return ResourceManager.GetString("ParseError_CSV_data_is_corrupt__closing_price_cannot_be_null_for_any_period", resourceCulture);
            }
        }
        
        internal static string PriceHistoryCsvFile_DetermineResolution_Unable_to_determine_PriceSeriesResolution_of_data_periods_in_CSV_data_ {
            get {
                return ResourceManager.GetString("PriceHistoryCsvFile_DetermineResolution_Unable_to_determine_PriceSeriesResolution" +
                        "_of_data_periods_in_CSV_data_", resourceCulture);
            }
        }
        
        internal static string PriceHistoryCsvFile_ParseDateColumn_Parsed_date_was_returned_as_null_or_whitespace_ {
            get {
                return ResourceManager.GetString("PriceHistoryCsvFile_ParseDateColumn_Parsed_date_was_returned_as_null_or_whitespac" +
                        "e_", resourceCulture);
            }
        }
        
        internal static string PriceHistoryCsvFile_SetResolution_Given_duration_represents_an_unknown_PriceSeriesResolution_ {
            get {
                return ResourceManager.GetString("PriceHistoryCsvFile_SetResolution_Given_duration_represents_an_unknown_PriceSerie" +
                        "sResolution_", resourceCulture);
            }
        }
        
        internal static string PriceSeriesRetrievalExtensions_UpdatePriceData_Parameter_provider_cannot_be_null_ {
            get {
                return ResourceManager.GetString("PriceSeriesRetrievalExtensions_UpdatePriceData_Parameter_provider_cannot_be_null_" +
                        "", resourceCulture);
            }
        }
        
        internal static string PriceSeriesRetrievalExtensions_UpdatePriceData_Paramter_priceSeries_cannot_be_null_ {
            get {
                return ResourceManager.GetString("PriceSeriesRetrievalExtensions_UpdatePriceData_Paramter_priceSeries_cannot_be_nul" +
                        "l_", resourceCulture);
            }
        }
        
        internal static string PriceSeriesRetrievalExtensions_UpdatePriceData_Provider_must_be_capable_of_providing_periods_of_resolution__0__or_better_ {
            get {
                return ResourceManager.GetString("PriceSeriesRetrievalExtensions_UpdatePriceData_Provider_must_be_capable_of_provid" +
                        "ing_periods_of_resolution__0__or_better_", resourceCulture);
            }
        }
        
        internal static string TransactionHistoryCsvFile_ParseDateColumn_Parsed_date_was_returned_as_null_or_whitespace_ {
            get {
                return ResourceManager.GetString("TransactionHistoryCsvFile_ParseDateColumn_Parsed_date_was_returned_as_null_or_whi" +
                        "tespace_", resourceCulture);
            }
        }
        
        internal static string TransactionHistoryCsvFile_ParseSymbolColumn_Parsed_ticker_symbol_was_returned_as_null_or_whitespace_ {
            get {
                return ResourceManager.GetString("TransactionHistoryCsvFile_ParseSymbolColumn_Parsed_ticker_symbol_was_returned_as_" +
                        "null_or_whitespace_", resourceCulture);
            }
        }
    }
}
