//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonneville.PriceTools.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonneville.PriceTools.Data.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to access the Internet to download price data..
        /// </summary>
        internal static string DownloadPricesToCsv_InternetAccessFailed {
            get {
                return ResourceManager.GetString("DownloadPricesToCsv_InternetAccessFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV data is corrupt; closing price cannot be null for any period..
        /// </summary>
        internal static string ParseError_CSV_data_is_corrupt__closing_price_cannot_be_null_for_any_period {
            get {
                return ResourceManager.GetString("ParseError_CSV_data_is_corrupt__closing_price_cannot_be_null_for_any_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine PriceSeriesResolution of data periods in CSV data..
        /// </summary>
        internal static string PriceHistoryCsvFile_DetermineResolution_Unable_to_determine_PriceSeriesResolution_of_data_periods_in_CSV_data_ {
            get {
                return ResourceManager.GetString("PriceHistoryCsvFile_DetermineResolution_Unable_to_determine_PriceSeriesResolution" +
                        "_of_data_periods_in_CSV_data_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get head using Price Series Resolution: {0}.
        /// </summary>
        internal static string PriceHistoryCsvFile_GetHead_Unable_to_get_head_using_Price_Series_Resolution {
            get {
                return ResourceManager.GetString("PriceHistoryCsvFile_GetHead_Unable_to_get_head_using_Price_Series_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get tail using Price Series Resolution: {0}.
        /// </summary>
        internal static string PriceHistoryCsvFile_GetTail_Unable_to_get_tail_using_Price_Series_Resolution {
            get {
                return ResourceManager.GetString("PriceHistoryCsvFile_GetTail_Unable_to_get_tail_using_Price_Series_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed date was returned as null or whitespace..
        /// </summary>
        internal static string PriceHistoryCsvFile_ParseDateColumn_Parsed_date_was_returned_as_null_or_whitespace_ {
            get {
                return ResourceManager.GetString("PriceHistoryCsvFile_ParseDateColumn_Parsed_date_was_returned_as_null_or_whitespac" +
                        "e_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Given duration represents an unknown PriceSeriesResolution..
        /// </summary>
        internal static string PriceHistoryCsvFile_SetResolution_Given_duration_represents_an_unknown_PriceSeriesResolution_ {
            get {
                return ResourceManager.GetString("PriceHistoryCsvFile_SetResolution_Given_duration_represents_an_unknown_PriceSerie" +
                        "sResolution_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a compatible type to implement interface: {0}..
        /// </summary>
        internal static string Serializer_DeserializeFromXml_Could_not_find_a_compatible_type_to_implement_interface___0__ {
            get {
                return ResourceManager.GetString("Serializer_DeserializeFromXml_Could_not_find_a_compatible_type_to_implement_inter" +
                        "face___0__", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed date was returned as null or whitespace..
        /// </summary>
        internal static string TransactionHistoryCsvFile_ParseDateColumn_Parsed_date_was_returned_as_null_or_whitespace_ {
            get {
                return ResourceManager.GetString("TransactionHistoryCsvFile_ParseDateColumn_Parsed_date_was_returned_as_null_or_whi" +
                        "tespace_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parsed ticker symbol was returned as null or whitespace..
        /// </summary>
        internal static string TransactionHistoryCsvFile_ParseSymbolColumn_Parsed_ticker_symbol_was_returned_as_null_or_whitespace_ {
            get {
                return ResourceManager.GetString("TransactionHistoryCsvFile_ParseSymbolColumn_Parsed_ticker_symbol_was_returned_as_" +
                        "null_or_whitespace_", resourceCulture);
            }
        }
    }
}
