//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonneville.PriceTools {
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonneville.PriceTools.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DateTimeExtensions_SeekPeriods_Unable_to_determine_boundaries_for_an_ITimePeriod_with_Resolution___0_ {
            get {
                return ResourceManager.GetString("DateTimeExtensions_SeekPeriods_Unable_to_determine_boundaries_for_an_ITimePeriod_" +
                        "with_Resolution___0_", resourceCulture);
            }
        }
        
        internal static string HoldingExtensions_GrossProfit_Cannot_calculate_profit_for_a_NULL_holding_ {
            get {
                return ResourceManager.GetString("HoldingExtensions_GrossProfit_Cannot_calculate_profit_for_a_NULL_holding_", resourceCulture);
            }
        }
        
        internal static string Order_Order_Cannot_create_an_Order_with_an_expiration_date_before_the_issue_date_ {
            get {
                return ResourceManager.GetString("Order_Order_Cannot_create_an_Order_with_an_expiration_date_before_the_issue_date_" +
                        "", resourceCulture);
            }
        }
        
        internal static string Order_Order_Invalid_OrderType_ {
            get {
                return ResourceManager.GetString("Order_Order_Invalid_OrderType_", resourceCulture);
            }
        }
        
        internal static string Order_Order_Invalid_PricingType_ {
            get {
                return ResourceManager.GetString("Order_Order_Invalid_PricingType_", resourceCulture);
            }
        }
        
        internal static string Order_Order_OrderType_must_be_Buy__Sell__SellShort__or_BuyToClose_ {
            get {
                return ResourceManager.GetString("Order_Order_OrderType_must_be_Buy__Sell__SellShort__or_BuyToClose_", resourceCulture);
            }
        }
        
        internal static string Order_Validate_Price_must_be_a_positive_number_ {
            get {
                return ResourceManager.GetString("Order_Validate_Price_must_be_a_positive_number_", resourceCulture);
            }
        }
        
        internal static string Order_Validate_Shares_must_be_a_positive_number_ {
            get {
                return ResourceManager.GetString("Order_Validate_Shares_must_be_a_positive_number_", resourceCulture);
            }
        }
        
        internal static string PriceSeries_GetDelegates_Resolution__0__not_supported_ {
            get {
                return ResourceManager.GetString("PriceSeries_GetDelegates_Resolution__0__not_supported_", resourceCulture);
            }
        }
        
        internal static string PriceSeries_GetLatestPrice_No_price_data_available_for_settlement_date___0_ {
            get {
                return ResourceManager.GetString("PriceSeries_GetLatestPrice_No_price_data_available_for_settlement_date___0_", resourceCulture);
            }
        }
        
        internal static string PriceSeries_GetPricePeriods_Unable_to_get_price_periods_using_resolution__0___Best_supported_resolution_is__1__ {
            get {
                return ResourceManager.GetString("PriceSeries_GetPricePeriods_Unable_to_get_price_periods_using_resolution__0___Bes" +
                        "t_supported_resolution_is__1__", resourceCulture);
            }
        }
        
        internal static string PriceSeriesImpl_Price_series_contains_no_price_periods_ {
            get {
                return ResourceManager.GetString("PriceSeriesImpl_Price_series_contains_no_price_periods_", resourceCulture);
            }
        }
        
        internal static string PriceSeriesReactionMovesExtensions_GetReactionMoves_Parameter_priceSeries_cannot_be_null_ {
            get {
                return ResourceManager.GetString("PriceSeriesReactionMovesExtensions_GetReactionMoves_Parameter_priceSeries_cannot_" +
                        "be_null_", resourceCulture);
            }
        }
        
        internal static string PriceTickImpl_PriceTickImpl_Quoted_price_must_be_greater_than_zero_ {
            get {
                return ResourceManager.GetString("PriceTickImpl_PriceTickImpl_Quoted_price_must_be_greater_than_zero_", resourceCulture);
            }
        }
        
        internal static string PriceTickImpl_PriceTickImpl_Quoted_volume__if_specified__must_be_greater_than_zero_ {
            get {
                return ResourceManager.GetString("PriceTickImpl_PriceTickImpl_Quoted_volume__if_specified__must_be_greater_than_zer" +
                        "o_", resourceCulture);
            }
        }
        
        internal static string ShareTransaction_Commission_Commission_must_be_greater_than_or_equal_to_0_ {
            get {
                return ResourceManager.GetString("ShareTransaction_Commission_Commission_must_be_greater_than_or_equal_to_0_", resourceCulture);
            }
        }
        
        internal static string ShareTransaction_OnSharesChanging_Shares_must_be_greater_than_or_equal_to_0_ {
            get {
                return ResourceManager.GetString("ShareTransaction_OnSharesChanging_Shares_must_be_greater_than_or_equal_to_0_", resourceCulture);
            }
        }
        
        internal static string ShareTransactionImpl_Commission_Commission_for_dividend_reinvestments_must_be_0_ {
            get {
                return ResourceManager.GetString("ShareTransactionImpl_Commission_Commission_for_dividend_reinvestments_must_be_0_", resourceCulture);
            }
        }
        
        internal static string SimplePeriod_SimplePeriod_Period_s_head_must_come_before_tail_ {
            get {
                return ResourceManager.GetString("SimplePeriod_SimplePeriod_Period_s_head_must_come_before_tail_", resourceCulture);
            }
        }
        
        internal static string StaticPricePeriodImpl_ConstructTail_Unable_to_identify_the_period_tail_for_resolution__0__ {
            get {
                return ResourceManager.GetString("StaticPricePeriodImpl_ConstructTail_Unable_to_identify_the_period_tail_for_resolu" +
                        "tion__0__", resourceCulture);
            }
        }
        
        internal static string StaticPricePeriodImpl_StaticPricePeriodImpl_Closing_price_cannot_be_higher_than_High_price_ {
            get {
                return ResourceManager.GetString("StaticPricePeriodImpl_StaticPricePeriodImpl_Closing_price_cannot_be_higher_than_H" +
                        "igh_price_", resourceCulture);
            }
        }
        
        internal static string StaticPricePeriodImpl_StaticPricePeriodImpl_Closing_price_cannot_be_lower_than_Low_price_ {
            get {
                return ResourceManager.GetString("StaticPricePeriodImpl_StaticPricePeriodImpl_Closing_price_cannot_be_lower_than_Lo" +
                        "w_price_", resourceCulture);
            }
        }
        
        internal static string StaticPricePeriodImpl_StaticPricePeriodImpl_Closing_price_must_be_greater_than_or_equal_to_zero_ {
            get {
                return ResourceManager.GetString("StaticPricePeriodImpl_StaticPricePeriodImpl_Closing_price_must_be_greater_than_or" +
                        "_equal_to_zero_", resourceCulture);
            }
        }
        
        internal static string StaticPricePeriodImpl_StaticPricePeriodImpl_Head_must_come_before_Tail_ {
            get {
                return ResourceManager.GetString("StaticPricePeriodImpl_StaticPricePeriodImpl_Head_must_come_before_Tail_", resourceCulture);
            }
        }
        
        internal static string StaticPricePeriodImpl_StaticPricePeriodImpl_High_price_must_be_greater_than_or_equal_to_zero_ {
            get {
                return ResourceManager.GetString("StaticPricePeriodImpl_StaticPricePeriodImpl_High_price_must_be_greater_than_or_eq" +
                        "ual_to_zero_", resourceCulture);
            }
        }
        
        internal static string StaticPricePeriodImpl_StaticPricePeriodImpl_Low_price_must_be_greater_than_or_equal_to_zero_ {
            get {
                return ResourceManager.GetString("StaticPricePeriodImpl_StaticPricePeriodImpl_Low_price_must_be_greater_than_or_equ" +
                        "al_to_zero_", resourceCulture);
            }
        }
        
        internal static string StaticPricePeriodImpl_StaticPricePeriodImpl_Opening_price_cannot_be_higher_than_High_price_ {
            get {
                return ResourceManager.GetString("StaticPricePeriodImpl_StaticPricePeriodImpl_Opening_price_cannot_be_higher_than_H" +
                        "igh_price_", resourceCulture);
            }
        }
        
        internal static string StaticPricePeriodImpl_StaticPricePeriodImpl_Opening_price_cannot_be_lower_than_Low_price_ {
            get {
                return ResourceManager.GetString("StaticPricePeriodImpl_StaticPricePeriodImpl_Opening_price_cannot_be_lower_than_Lo" +
                        "w_price_", resourceCulture);
            }
        }
        
        internal static string StaticPricePeriodImpl_StaticPricePeriodImpl_Opening_price_must_be_greater_than_or_equal_to_zero_ {
            get {
                return ResourceManager.GetString("StaticPricePeriodImpl_StaticPricePeriodImpl_Opening_price_must_be_greater_than_or" +
                        "_equal_to_zero_", resourceCulture);
            }
        }
        
        internal static string StaticPricePeriodImpl_StaticPricePeriodImpl_Volume_must_be_greater_than_or_equal_to_zero_ {
            get {
                return ResourceManager.GetString("StaticPricePeriodImpl_StaticPricePeriodImpl_Volume_must_be_greater_than_or_equal_" +
                        "to_zero_", resourceCulture);
            }
        }
        
        internal static string StaticPricePeriodImpl_this_Index_was_before_the_head_of_the_price_period_ {
            get {
                return ResourceManager.GetString("StaticPricePeriodImpl_this_Index_was_before_the_head_of_the_price_period_", resourceCulture);
            }
        }
        
        internal static string StockIndexInfo_GetTickers_Unknown_stock_index___0_ {
            get {
                return ResourceManager.GetString("StockIndexInfo_GetTickers_Unknown_stock_index___0_", resourceCulture);
            }
        }
        
        internal static string TimePeriodImpl_this_Date_time___0__is_out_of_range_for_this_price_period_ {
            get {
                return ResourceManager.GetString("TimePeriodImpl_this_Date_time___0__is_out_of_range_for_this_price_period_", resourceCulture);
            }
        }
        
        internal static string TimeSeriesExtensions_GetTimePeriods_Unable_to_get_time_periods_using_resolution__0___Best_supported_resolution_is__1__ {
            get {
                return ResourceManager.GetString("TimeSeriesExtensions_GetTimePeriods_Unable_to_get_time_periods_using_resolution__" +
                        "0___Best_supported_resolution_is__1__", resourceCulture);
            }
        }
        
        internal static string TransactionFactory_ConstructCashTransaction_Cannot_create_a_CashTransaction_for_an_OrderType_of__0__ {
            get {
                return ResourceManager.GetString("TransactionFactory_ConstructCashTransaction_Cannot_create_a_CashTransaction_for_a" +
                        "n_OrderType_of__0__", resourceCulture);
            }
        }
        
        internal static string TransactionFactory_CreateTransaction_Unknown_OrderType___0_ {
            get {
                return ResourceManager.GetString("TransactionFactory_CreateTransaction_Unknown_OrderType___0_", resourceCulture);
            }
        }
    }
}
