//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sonneville.PriceTools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sonneville.PriceTools.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument index must be a date within the span of this Indicator..
        /// </summary>
        internal static string IndicatorError_Argument_index_must_be_a_date_within_the_span_of_this_Indicator {
            get {
                return ResourceManager.GetString("IndicatorError_Argument_index_must_be_a_date_within_the_span_of_this_Indicator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add this transaction to the position..
        /// </summary>
        internal static string Position_AddTransaction_Cannot_add_this_transaction_to_the_position_ {
            get {
                return ResourceManager.GetString("Position_AddTransaction_Cannot_add_this_transaction_to_the_position_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticker must not be null, empty, or whitespace..
        /// </summary>
        internal static string Position_OnTickerChanging_Ticker_must_not_be_null__empty__or_whitespace_ {
            get {
                return ResourceManager.GetString("Position_OnTickerChanging_Ticker_must_not_be_null__empty__or_whitespace_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission for {0} transactions must be 0..
        /// </summary>
        internal static string ShareTransaction_Commission_Commission_for__0__transactions_must_be_0_ {
            get {
                return ResourceManager.GetString("ShareTransaction_Commission_Commission_for__0__transactions_must_be_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission must be greater than or equal to 0..
        /// </summary>
        internal static string ShareTransaction_Commission_Commission_must_be_greater_than_or_equal_to_0_ {
            get {
                return ResourceManager.GetString("ShareTransaction_Commission_Commission_must_be_greater_than_or_equal_to_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shares must be greater than or equal to 0..
        /// </summary>
        internal static string ShareTransaction_OnSharesChanging_Shares_must_be_greater_than_or_equal_to_0_ {
            get {
                return ResourceManager.GetString("ShareTransaction_OnSharesChanging_Shares_must_be_greater_than_or_equal_to_0_", resourceCulture);
            }
        }
    }
}
